=== jleocan773/JonathanLeon_UD4_LMSGI/Actividades/Clientes/mejoraclientes.dtd
<!ELEMENT clientes (cliente*)>
    <!ELEMENT cliente (sede_alta*, cliente_direccion, cod_cliente, num_viviendas, coste_viviendas, resumen_viviendas, plazo)>
        <!ELEMENT sede_alta (sede_direccion, cod_sede, empleado_alta, fecha_alta, descripcion_cliente)>
             <!ELEMENT sede_direccion (#PCDATA)>
             <!ELEMENT cod_sede  (#PCDATA)>
             <!ELEMENT empleado_alta  (#PCDATA)>
             <!ELEMENT fecha_alta  (#PCDATA)>
             <!ELEMENT descripcion_cliente  (#PCDATA)>
        <!ELEMENT cliente_direccion (#PCDATA)>
        <!ELEMENT cod_cliente (#PCDATA)>
        <!ELEMENT num_viviendas (#PCDATA)>
        <!ELEMENT coste_viviendas (#PCDATA)>
        <!ELEMENT resumen_viviendas (#PCDATA)>
        <!ELEMENT plazo (#PCDATA)>

=== jleocan773/JonathanLeon_UD4_LMSGI/Actividades/Clientes/mejoraclientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "mejoraclientes.dtd">
<clientes>
    <cliente>
        <sede_alta>
            <sede_direccion></sede_direccion>
            <cod_sede>X2345678</cod_sede>
            <empleado_alta></empleado_alta>
            <fecha_alta></fecha_alta>
            <descripcion_cliente></descripcion_cliente>
        </sede_alta>
        <cliente_direccion></cliente_direccion>
        <cod_cliente></cod_cliente>
        <num_viviendas></num_viviendas>
        <coste_viviendas></coste_viviendas>
        <resumen_viviendas></resumen_viviendas>
        <plazo></plazo>
    </cliente>
</clientes>
