=== jleocan773/JonathanLeon_UD4_LMSGI/Actividades/Biblioteca/BibliotecaBestSellers2022.dtd
<!ELEMENT libreria (libro*)>
<!ELEMENT libro (autores*,genero,idioma-original,titulo,editorial,ISBN,fechaPublicacion)>
<!ATTLIST libro id CDATA #REQUIRED>
<!ELEMENT autores (autor*)>
<!ELEMENT autor (nombre,apellido1,apellido2)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido1 (#PCDATA)>
    <!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT idioma-original (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>

=== jleocan773/JonathanLeon_UD4_LMSGI/Actividades/Biblioteca/BibliotecaBestSellers2022.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "BibliotecaBestSellers2022.dtd">
<libreria>
<libro id="1">
    <autores>
        <autor>
            <nombre>Dolores </nombre>
            <apellido1>Redondo </apellido1>
            <apellido2>García </apellido2>
        </autor>
    </autores>
    <genero>Aventura, Misterio</genero>
    <idioma-original>Español</idioma-original>
    <titulo>Esperando al Diluvio</titulo>
    <editorial>Casa del Libro</editorial>
    <ISBN>9788730480866</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="2">
    <autores>
        <autor>
            <nombre>Luz </nombre>
            <apellido1>Gabas </apellido1>
            <apellido2>Perez </apellido2>
        </autor>
    </autores>
    <genero>Fantasía, Aventura</genero>
    <idioma-original>Español</idioma-original>
    <titulo>Lejos de Luisiana</titulo>
    <editorial>Casa del Libro</editorial>
    <ISBN>9789826497522</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="3">
    <autores>
        <autor>
            <nombre>Juan </nombre>
            <apellido1>Gomez </apellido1>
            <apellido2>Jurado </apellido2>
        </autor>
    </autores>
    <genero>Crimen, Mafia</genero>
    <idioma-original>Español</idioma-original>
    <titulo>Todo Arde</titulo>
    <editorial>Casa del Libro</editorial>
    <ISBN>9789218026293</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="4">
    <autores>
        <autor>
            <nombre>Arturo </nombre>
            <apellido1>Perez </apellido1>
            <apellido2>Reverte </apellido2>
        </autor>
    </autores>
    <genero>Guerra, Histórico</genero>
    <idioma-original>Español</idioma-original>
    <titulo>Revolución</titulo>
    <editorial>Casa del Libro</editorial>
    <ISBN>9787434788322</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="5">
    <autores>
        <autor>
            <nombre>Almudena </nombre>
            <apellido1>Grandes </apellido1>
            <apellido2>Rioja </apellido2>
        </autor>
    </autores>
    <genero>Novela, Contemporánea</genero>
    <idioma-original>Español</idioma-original>
    <titulo>Todo va a Mejorar</titulo>
    <editorial>Casa del Libro</editorial>
    <ISBN>9784290637665</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="6">
    <autores>
        <autor>
            <nombre>Margarent</nombre>
            <apellido1>Colleen</apellido1>
            <apellido2>Fennel</apellido2>
        </autor>
    </autores>
    <genero>Juvenil, Romance</genero>
    <idioma-original>Inglés</idioma-original>
    <titulo>Volver a Empezar</titulo>
    <editorial>Planeta</editorial>
    <ISBN>9788408267195</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="7">
    <autores>
        <autor>
            <nombre>Stephen</nombre>
            <apellido1>Edwin</apellido1>
            <apellido2>King</apellido2>
        </autor>
    </autores>
    <genero>Literatura Fantástica, Suspense, Fantasía Oscura</genero>
    <idioma-original>Inglés</idioma-original>
    <titulo>Cuento de Hadas</titulo>
    <editorial>Plaza &amp; Janes Editores</editorial>
    <ISBN>9788401027710</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="8">
    <autores>
        <autor>
            <nombre>Jeffrey </nombre>
            <apellido1>Patrick </apellido1>
            <apellido2>Kinney</apellido2>
        </autor>
    </autores>
    <genero>Ficción, Literatura Infantil, Novela Gráfica, Humor </genero>
    <idioma-original>Inglés</idioma-original>
    <titulo>Diario de Greg 17 - Dando la nota</titulo>
    <editorial>Molino</editorial>
    <ISBN>9788427226166</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="9">
    <autores>
        <autor>
            <nombre>Lucy</nombre>
            <apellido1>Foley</apellido1>
            <apellido2>Adams</apellido2>
        </autor>
    </autores>
    <genero>Suspenso, Misterio, Ficción</genero>
    <idioma-original>Inglés</idioma-original>
    <titulo>El Apartamiento de París</titulo>
    <editorial>Harpercollins Pub</editorial>
    <ISBN>9780008384982</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
<libro id="10">
    <autores>
        <autor>
            <nombre>Margarent</nombre>
            <apellido1>Colleen</apellido1>
            <apellido2>Fennel</apellido2>
        </autor>
    </autores>
    <genero>Novela Rosa, Romance, Ficción</genero>
    <idioma-original>Inglés</idioma-original>
    <titulo>Recuerdos de Él</titulo>
    <editorial>Amazon Crossing</editorial>
    <ISBN>9781542025607</ISBN>
    <fechaPublicacion>2022</fechaPublicacion>
</libro>
</libreria>
